language: python

python:
- 3.7
- 3.7-dev

before_install:
- sudo apt-get update
- sudo apt-get -y install python-pip
- sudo pip install --upgrade pip
- pip install --upgrade pip
- pip install codecov
- pip install pycodestyle
- pip install pydocstyle
- pip install tox
- pip install pytest
- pip install python-coveralls

install:
- pip install -r requirements.txt

before_script:
  - sleep 10

script:
- coverage run tests.py
- codecov
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
after_success:
- coverage combine && codecov
- coveralls
notifications:
  email:
    on_success: never
    on_failure: always
